# Generated by Django 4.2.1 on 2023-05-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_driverfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdetails',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
